{
  "hash": "634c92d7890a08c6ad93a802c431d922",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Notes: A series on probability\"\ndraft: true\n---\n\n\n\nThe following will be a series of blog posts containing notes of my attempt to better understand probability theory.\nThe intent is to take the theory in bite-sized chunks, while also taking the opportunity to dig further into concepts that require greater depth.\nThe overall goal of this series is to put the concepts into my own words, developing my own examples to better understand the foundations of the theory.\n\nProbability theory is a deep subject.\nA single blog post, and a series of notes for that matter, would be insufficient to provide much depth.\nMany texts already provide detailed coverage of this subject.\nThis blog post, rather, is an attempt to wrestle with and make sense of the theory's basic concepts step-by-step.\nI'll list relevant references and additional readings at the end of each post.\n\nBe aware, there will likely be errors in this series.\nLearning is messy.\nI may, at times, misunderstand or misinterpret portions of the theory's concepts.\nAs such, you'll want to verify any of my work against other reliable, peer-reviewed sources from subject matter experts.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.1     ✔ stringr   1.5.2\n✔ ggplot2   4.0.0     ✔ tibble    3.3.0\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.1.0     \n── Conflicts ────────────────────────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\n# set random seed for reproducibility\nset.seed(20250908)\n```\n:::\n\n\n\n# What is probability?\n\nProbability is a mathematical framework to model the outcomes of random processes.\nSince it's a framework, some have provided a formal definition.\n\nAccording to [@diezMineBarr2019], probability is defined as:\n\n> The proportion of times the outcome would occur if we observed the random process an infinite number of times.\n\nFrom the archived [Seeing Theory website](https://seeing-theory.brown.edu/index.html#firstPage), probability is defined as:\n\n> Probability theory is the mathematical framework that allos us to analyze chance event in a logically sound manner.\n\nFrom Wikipedia:\n\n> Probability is a branch of mathematics and statistics concerning events and numerical descriptions of how likely they are to occur.\n\nIf you're looking for the 'classical definition of probabiliyt', you'll be directed to the following definition:\n\n> \n\nOther online sources define probability as:\n\n> Probability is defined as the likelihood of the occurrence of any event.\n\nSpend any time searching for a clear, complete definition of probability will lead you to various technical definitions.\n\n## Outcomes\n\nProbability is a method for quantifying outcomes and uncertainty.\nThese outcomes can be singular, like rolling a six-sided die or drawing one card from a [standard deck of playing cards](https://en.wikipedia.org/wiki/Standard_52-card_deck).\nThese outcomes might also be more practical.\nFor example, examining the results of an email marketing campaign.\n\nProbability is also useful for modeling collections of outcomes, also known as events.\nFor instance, calculating the probability of rolling an even number of a six-sided die (e.g., roll = {2, 4, 6}).\nEvents can either be *disjoint* (i.e., *mutually exclusive*) or *not disjoint*.\nI find examples using a six-sided dice to be the most straight forward explanation of this concept.\n\nWhen you roll a single six-sided die, there's only one outcome that can result (i.e., roll = {1, 2, 3, 4, 5, 6}).\nLet's say we roll the die once.\nWhat is the probability a 2 or a 4 will be the outcome of our roll.\nThese two potential outcomes are disjoint: they can't happen at the same time.\nHow, then, do we go about determining the chance we'll roll a 2 or a 4?\n\n## The basic rules of probability\n\nAs a theory, probability follows specific rules.\nThese rules are listed and discussed further below.\n\n### Possible values of probability\n\nProbabilities are represented as proportions, ranging from 0 and 1.\nOften, probability is represented using percentages: 0% to 100%.\n\nGiven probabilities are a proportion, the sum of all possible outcomes is equal to 1.\n\n### Addition rule\n\nWhen outcomes are disjoint, the addition rule of disjoint outcomes is used to calculate the probability.\nIn equation form, the calculation looks like this:\n\n$$\nP(rolling a 2 or 4) = P(2) + P(4)\n\\frac{1}{6} + \\frac{1}{6}\n\\frac{2}{6} = \\frac{1}{3}\n$$\n\nIf you have more than two events, for instance the probability of rolling an even number, the equation can be expanded:\n\n$$\nP(rolling a 2, 4, or 6) = P(2) + P(4) + P(6)\n\\frac{1}{6} + \\frac{1}{6} + \\frac{1}{6}\n\\frac{3}{6} = \\frac{1}{2}\n$$\n\nAgain, this only applies when the outcomes being observed are considered to be disjoint.\n\nLet's use a little R code to simulate this a bit.\nLet's simulate the roll of a six-sided die 10000 times, and view the distrubutions of the outcomes.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(sample(1:6, 10000, replace = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   1    2    3    4    5    6 \n1693 1685 1626 1635 1680 1681 \n```\n\n\n:::\n\n```{.r .cell-code}\nprop.table(table(sample(1:6, 10000, replace = TRUE)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n     1      2      3      4      5      6 \n0.1646 0.1637 0.1648 0.1722 0.1651 0.1696 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Probability of rolling a 2 or 4\n.1607 + .1675\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3282\n```\n\n\n:::\n\n```{.r .cell-code}\n# Probability of rolling an even number\n.1607 + .1675 + .1686\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4968\n```\n\n\n:::\n:::\n\n\n\nAs you can see, the probability calculated from the outcomes are close to what we initially estimated.\n\n## Not disjoint events and the general addition rule\n\nCalculating the probability for not disjoint events requires a different approach.\nWhen calculating the probability of not disjoint events, the General Addition Rule is used.\nThis probability calculation accounts for overlapping events.\nFor instance, let's use a marketing example.\n\nSay we are a marketing department rolling out a new campaign along with a sales premimum for some of our products (e.g., a buy one get one free offer).\nAs part of the analysis, we include 10,000 recent sales transactions.\nOf those 10,000 sales:\n\n* 2,578 interacted with the campaign.\n* 1,256 of the sales transactions used the premimum offer.\n* 725 sales involved both an interaction with the campaign and took advantage of the premium offer.\n\nHere we have a situation where the events are not disjoint, so we need to use the General Addition rule to calculate probabilities.\nA Venn diagram is a useful visualization to help organize and calculate the probabilities of the different events.\n\nFor instance, we can see the probability that a sale is the result of at least an interaction with the marketing campaign is .2578 (i.e., 2578 / 10000 = .2578).\nFor the premium, the probability is .1256 (i.e., 1256 / 10000 = .1256).\n\nHowever, how can we calculate the probability a randomly drawn sales transaction is due to either an interaction with the marketing campaign or the sales premium?\nThe General Addition Rule can be used to calculate this probability.\nThe General Addition Rule equation look like this:\n\n$$\nP(A or B) = P(A) + P(B) - P(A and B)\n$$\n\nHere's how to use the general addition rule applied to our email marketing example:\n\n$$\nP(interacted with campaign or used premimum) = P(interacted with campaign) + P(used premium) - P(interacted with campaign and used premimum)\nP(interacted with campaign) + P(used premium) - P(interacted with campaign and used premimum)\n.2578 + .1256 - .0725\n.3109\n$$\n\nGiven the 10,000 sales interactions, the probability that a sale took place because of an interaction with the marketing campaign or the sales premium is 31.09%.\n\n### Multiplication rule\n\n\n\n### Conditional probability\n\nConditional probabilities involve calculating relationships between two or more variables.\nAlong with conditional probabilities, you can also calculate marginal and joint probabilities.\nMarginal probabilities are probabilities that involve only one variable.\nJoint probabilities are calculations based on two or more variables.\n\nContingency tables are a useful tool for exploring conditional probabilities.\nLet's use a marketing example once again.\nSay we're a company soon to launch a new product.\nAs part of the product launch, an email campaign will be created.\n\nIn this example, we have two variables of interest: `email_event` and `transaction`.\nThe outcomes of each variable include:\n\n* `email_event` = {`click`, `no_click`}\n* `transaction` = {`purchase`, `no_purchase`}\n\nBelow are contrived values of the outcomes of our fictious email campaign.\n\n| Email    | Purchase | No Purchase | Total |\n|----------|----------|-------------|-------|\n| click    | 1576     | 3755        | 5331  |\n| no_click | 5476     | 750         | 6226  |\n| Total    | 7052     | 4505        | 11557 |\n\nWith the frequencies of the different events, we can calculate our marginal and joint probabilities.\nLet's start with the probability that someone clicked the link in our product email.\nThe calculation would be the following:\n\n$$\nP(`click`) = \\frac{5331}{11557} = .4613\n$$\n\nWhat about those that clicked, but didn't make a purchase?\nThe calculation would look like the following:\n\n$$\nP(`Email` is `click` and `Purchase` is `no_purchase`) = \\frac{3755}{11557} = 0.325\n$$\n\nSay we want the joint probability of email recipients who clicked and made a purchase.\nWe can do the following:\n\n$$\nP(`Email` is `click` and `Purchase` is `purchase`) = \\frac{1576}{11557} = 0.1363\n$$\n\nNot a bad conversion rate for the campaign.\n\nIt's often useful to convert contingency table's values into a table of proportions.\nFor instance, the proportions for our above example would look like the following:\n\n| Email    | Purchase | No Purchase | Total  |\n|----------|----------|-------------|--------|\n| click    | 0.1364   | 0.3249      | 0.4613 |\n| no_click | 0.4738   | 0.0649      | 0.5387 |\n| Total    | 0.6102   | 0.3898      | 1.00   |\n\nIndeed, you might recognize some of these estimates are the same as what we calculated above.\n\nWe can also improve our probability estimate of one variable using information from another.\nThis is where conditional probabilities come into play.\nConditional probabilities are probabilities calculated under some condition.\nConditional probabilites are composed of two parts:\n\n1. An outcome of interest\n2. A condition\n\nSay we wanted to get better information about whether a click led to a purchase or not.\nWe could narrow our focus to just clicks (i.e., our condition) to get a better estimate of the probability of a purchase.\nThis is a conditional probability.\nThe condition being that someone clicked a link within our email.\nIn equation form, it would look something like this:\n\n$$\nP(`transaction` is `purchase` given `email event` is `click`) = \\frac{1576}{5331} = .2956\n$$\n\nHow about the conditional probability when someone clicked and no purchase took place.\nIn other words, P(`transaction` is `purchase` | `email event` is `click`).\n\n$$\nP(`transaction` is  `purchase` |  `email event` is  `click`) = \\frac{3755}{5331} = .7044\n$$\n\n## References and further readings\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}