---
title: "The Hex Update: Issue 032"
date: "2026-07-06"
author: "Collin K. Berke, Ph.D."
description: "Some more data points showing bot traffic now outnumbers human traffic; AI news now complaining about... AI news; a report on the connected TV interfaces that stand out, and others that don't; a peek behind the scenes of Jim Henson's Creature Shop; and some other cool things I came across this week"
format:
  html:
    link-external-newwindow: true
toc: true
from: markdown+emoji
categories:
  - the hex update
  - media
---

# Let's catch up

Welcome to Issue 032.

For the U.S. folks, I hope you had a happy, relaxing 4th of July 🎆.
This holiday always serves as a reminder to enjoy the summer months.
For fellow readers outside of the U.S., I hope you still had a wonderful weekend.

With that, let's get back to it.

Three topics recently caught my attention:

* [Some more data points about how bot traffic now outnumbers human traffic](https://www.cnet.com/tech/services-and-software/bots-now-outnumber-humans-on-the-internet-heres-what-that-actually-means/)
* [AI news now complaining about... AI news](https://www.niemanlab.org/2026/07/now-were-getting-ai-fake-news-complaining-about-how-ai-fake-news-is-the-death-of-real-news/)
* [A report on the connected TV interfaces that stand out, and the others that don't](https://us-ctv-ui-review.lovable.app/)

For a bit of fun, I share an [article](https://www.smithsonianmag.com/travel/a-peek-inside-jim-hensons-creature-shop-where-sesame-street-characters-and-other-whimsical-puppets-are-designed-180989051/) giving a behind the scenes look at [Jim Henson's Creature Shop](https://en.wikipedia.org/wiki/Jim_Henson%27s_Creature_Shop).

You'll also find some additional links to other items I found cool this week.

# Three things

Here's what caught my attention this week:

### [Bots Now Outnumber Humans Online. Here's Why It Matters.](https://www.cnet.com/tech/services-and-software/bots-now-outnumber-humans-on-the-internet-heres-what-that-actually-means/) (article)

This brief article reports recent findings from [Cloudflare's](https://en.wikipedia.org/wiki/Cloudflare) bot and AI internet traffic measurement tools.
These tools find AI agents and bots account for 54.7% of web requests, which is a trend that happened much faster than many expected.
The article further clarified this traffic is agent bots associated with AI chatbot searching the internet on behalf of users.
As such, the article mentions increased support for the [*Dead Internet Theory*](https://en.wikipedia.org/wiki/Dead_Internet_theory), which asserts current online traffic is mostly being generated by bots and AI.
This quote highlights a key point from the article:

> Humans still physically engage with content more than AI does, but AI visits webpages more often.

The article also cited some reporting related to how much content is being produced by AI, including social media posts, track uploads to streaming music services, and online articles.

#### Why does this matter?

The speed of this trend is what matters here.
Agentic AI traffic will only continue to increase, especially with the introduction of additional agentic tools into [Google Search](https://www.npr.org/2026/05/22/nx-s1-5829915/google-search-box-ai) and other platforms.
Publishers will want to continue to track AI agentic requests to their digital properties, [as it has a real dollar amount associated with them, and some may provide no value](https://www.adexchanger.com/ai/how-much-are-bots-costing-you-iab-tech-lab-wants-content-owners-to-find-out/).

### [Now we’re getting AI fake news complaining about how AI fake news is the death of real news](https://www.niemanlab.org/2026/07/now-were-getting-ai-fake-news-complaining-about-how-ai-fake-news-is-the-death-of-real-news/) (article)

Here's an interesting piece reporting on a instance where an AI-generated news site was publishing fake stories about the shuttering and takeover of other real and fake news sites.
The article sought to explore why such a site existed and to better understand the reason these sources were publishing such articles.
Despite uncovering some plausible explanations, the article provides an additional reason for why this case matters: it's a reminder of how good AI has come and how easy it is now to create realistic, believable publications.
The final line from the article summarizes this point clearly:

> It’s a useful reminder that AI has made fakery easy enough that it can come from unexpected directions — even in a niche you know a lot about and which you wouldn’t expect to be worth the effort.

#### Why does this matter

This article serves as a reminder of how easy it is to create a fake news publication with realistic looking articles.
Ethical and media literacy considerations aside, from a media organization perspective, this is just more noise in the information ecosystem to contend with.
As such, legitimate news organizations will want to consider strategies and tactics to shore up audience trust.
Such efforts must also strive to serve as a signal that the organization's mission has audience's best interest in mind, and that they uphold themselves to the highest of journalistic standards.

### [Some CTV interfaces stand out. Some fall short.](https://us-ctv-ui-review.lovable.app/) (report)

This is an interactive report on [connected TV](https://en.wikipedia.org/wiki/Smart_TV) interfaces for several services.
It categorizes different CTV platform interfaces into what 'stood out', what 'gave reviewers pause', and some that are 'worth noting'.
Along with listing the platforms that fall into these categories, the report included additional details on why each interface was included within each category.
Some details highlighted on the interfaces that stood out include:

* A high-impact hero banner
* Clean row-based layouts
* Fast navigation
* Smart personalization opportunities
* Minimal left-side navigation.

#### Why does this matter

Interfaces are now how audiences initially interact with content.
It's the first experience audiences have when turning on their TVs.
Seeing how the large platforms do it is critical.
Indeed, smaller media organizations may not be able to maintain the development pace of large streaming services.
However, what can be done is to learn from what does well on these interfaces and what doesn't do well, so as to include some of the high-impact design elements.

Check out the links above for the full story in each item, not just my brief summary and analysis.

# What I found interesting this week

I'm still continuing to build CLI tools with [`Rapp`](https://github.com/r-lib/Rapp).
Some of these tools have included the use of the [`system2()`](https://rdrr.io/github/robertzk/monadicbase/man/system2.html) function to run commands from the shell.
These commands often require a library to be installed from some external source.
So, if my intention is to wrap these tools into an R package and share with others, then I need to do some validation checking of the user's environment to ensure they have what's needed to run on their system.
I was able to create a simple function to do this type of validation checking, while also informing users what to do if they don't have the needed dependencies installed.

## Cool things I recently bumped into

A collection of links to things I've found cool recently (or was reminded are cool).

* [A Peek Inside Jim Henson’s Creature Shop, Where ‘Sesame Street’ Characters and Other Whimsical Puppets Are Designed](https://www.smithsonianmag.com/travel/a-peek-inside-jim-hensons-creature-shop-where-sesame-street-characters-and-other-whimsical-puppets-are-designed-180989051/) (article)
* [Space Elevator](https://neal.fun/space-elevator/) (interactive site)
* [Be reckless](https://benn.substack.com/p/be-reckless) (article)
* [The Internet I Grew Up With Doesn't Exist Anymore](https://cleberg.net/blog/internet.html) (blog post)

That's it for this update.
I hope you have a good, productive week.

Onwards! 🚀

# Let's connect

If you found this content useful, please share.
If you find these topics interesting and want to discuss further, let's connect:

{{< include ../../../.includes/_connect.qmd >}}
