project:
  type: website

website:
  title: "Collin K. Berke, Ph.D."
  favicon: icon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - now.qmd
      - blog/index.qmd
      - til/index.qmd

format:
  html:
    theme: 
      dark: superhero
      light: flatly 
    css: styles.css
    toc: false 
    page-layout: full



