project:
  type: website

website:
  title: "Collin K. Berke, Ph.D."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - now.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



