project:
  type: website

execute:
  freeze: true

website:
  title: "Collin K. Berke, Ph.D."
  favicon: icon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - now.qmd
      - blog/index.qmd
      - say-hi.qmd

format:
  html:
    theme:
      dark: [superhero, theme-dark.scss]
      light: flatly
    css: styles.css
    toc: false
    page-layout: full
