---
title: "Past Now Page Updates"
subtitle: "Here you'll find old updates I've removed from my Now Page."
format:
  html:
    toc: false
    date-modified: "2024-12-14"
---

# 2024-12-14 update

#### Burning it all down and building it back up, my [Neovim](https://neovim.io/) setup

It was inevitable; I'm revamping my Neovim configuration. It started with a kickstarter, but now I'm looking to further customize. I'm also attempting to address some bugs that have creeped into my configuration. I've recently come to the conclusion that I need to burn everything down and start anew. Alas, I'm not weary. It's another great learning experience.

#### Attended [Posit::conf(2023)](https://posit.co/conference/) Chicago

I was fortunate to attend this year's Posit conference in Chicago, a five day conference with workshops and speaker sessions. I'm still sorting through all that I learned. Here are some of the highlights:

* Attending the Introduction to Tidymodels workshop
* Attending the Package Development Masterclass workshop
* All the keynote speakers, especially J.D. Long's *It's Abstractions All the Way Down* talk.
* Networking and meeting some folks from the [R4DS Online Learning Community](https://rfordatasci.com/) (in person).

#### Experimenting more with Tableau and `plotly`

> If the only tool you have is a hammer, it is tempting to treat everything as if it were a nail. 
>
> \- Abraham Maslow

Although I prefer to do the majority of my analysis and visualization work using code based tools like R, I'm attempting to broaden my experience by experimenting more with different BI tools. This includes [Tableau](https://www.tableau.com/). I've also been experimenting with creating interactive data visualizations with [`plotly`](https://plotly.com/r/). To develop these skills, I've been contributing to the [#tidytuesday](https://github.com/rfordatascience/tidytuesday) social data project. Check out my recent [blog posts](https://www.collinberke.com/blog/) to view my contributions. If you're interested in what I've created using Tableau, check out my [public profile](https://public.tableau.com/app/profile/collin.berke/vizzes).

# 2024-03-17 update

#### Working on a 30 day `tidymodels` `recipes` package challenge

I've been developing my machine learning and modeling skills. Specifically, I've been focusing on learning the various steps to preprocess data for modelling and feature engineering. This includes becoming more proficient with the [`tidymodels`](https://www.tidymodels.org/) [`recipes`](https://recipes.tidymodels.org/) package. [Check out my post](https://www.collinberke.com/blog/posts/2024-01-01-30-days-challenge-tidymodels-recipes/) to keep up with the latest.

#### Continuing to experiment with [Neovim](https://neovim.io/)

I've heavily leaned into using [Neovim](https://neovim.io/) for most of my workflows. During this transition, I've come across some really useful tools, like [`telescope`](https://github.com/nvim-telescope/telescope.nvim), [`harpoon`](https://github.com/ThePrimeagen/harpoon), and [`vim-fugitive`](https://github.com/tpope/vim-fugitive). I'm trying to learn as much as I can, as I still don't know if my configuration is correct ... lol

# 2024-01-15 update

#### It's a Python summer

This summer I've been focusing on developing my [Python](https://www.python.org/) programming skills. I have a pretty good handle of R, so I felt it was time to learn Python. This started with learning Python's basic data types, struggling through understanding [Numpy arrays](https://numpy.org/doc/1.25/), getting a handle on the extensive use cases of the [pandas](https://pandas.pydata.org/) library, and learning how to manage environments using [conda](https://docs.conda.io/en/latest/). I'm aiming to write more blog posts focused in this space to document what I'm learning.

# Pre 2024-01-15 updates

#### Project Conduit 

Currently developing and maintaining a data pipeline project built using R and Python. Technology utilized includes Google Cloud resources, Docker, Apache Airflow, Google BigQuery, Google Analytics, Google Data Studio, and Shiny. The goal is to centralize and automate data processing, storage, and reporting.  

#### R for Data Science Online Learning Community book club facilitator

Recently started facilitating an [R for Data Science Online Learning Community](https://www.rfordatasci.com/) online book club (check it out by joining the [Slack workspace](http://r4ds.io/join)). This group is currently reading through Hadley Wickham's [Advanced R](https://adv-r.hadley.nz/) book. The group meets weekly online over Zoom. Meetings are open to anyone who is a part of the Slack group (Join the #book_club-advr channel to keep up with the book club). Check out the playlist of past meeting recordings [here](https://www.youtube.com/watch?v=vfTg6upHvO4&list=PL3x6DOfs2NGi4I1DhjPufFNbqCry_xQLq). I would love for more to join and be a part of this group. 

#### Experimenting with [Neovim](https://neovim.io/)

I've been experimenting more and more with Neovim for my development work. I'm becoming more comfortable with the different modes, movements, actions, and various tools for editing text and code. Still struggling through the configuration and plugin ecosystem to set up workflows that are the most productive. Going through this process has been a challenge, but has me really reflecting on how I approach my work, evaluating what is needed, not needed, and focusing on the bad habits I need to break.  
