---
title: "Now"
subtitle: "Here you'll find what I'm currently up to."
format:
  html:
    toc: false
    date-modified: "2024-12-14"
---

A now page, [why?](https://nownownow.com/about)

## Projects I'm working on

#### Transitioning to LazyVim

As of my last update, I decided to burn down my Neovim setup and start over.
I was in search of something more enjoyable and manageable to work with.
I came across [LazyVim](https://www.lazyvim.org/) and started to really enjoy it.
Out of the box it had sane defaults and configurations, so the setup was minimal and I've found it more enjoyable to work with.
LazyVim Extras also make it easy to install and configure different plugins.

#### Blogging more

I'm attempting to increase the publishing of my blog posts.
I was following a cadance of roughly posting every month.
I want to bump this up to two a month, with a stretch goal being every week.
The hardest parts are being realistic with myself, identifying shorter post topics to write about, and being kinder to myself.
Writing posts with a tighter turn-around means embracing progress over perfection.

#### Thinking about the use of data and organizational culture

More and more often I'm being tasked with stratigizing how to improve the role and impact data has within an organization.
These are not easy questions to answer.
I've been doing a lot of exploring and experimentation.
If anyone has any suggestions, let's chat.

If you're interested in what I've focused on in the past, [check out my past updates](https://collinberke.com/now-old.html)

## Books I'm reading

## A list of books I've read (ever since I've started keeping track)

#### [Practical SQL, 2nd Edition: A Beginner's Guide to Storytelling with Data](https://www.amazon.com/Practical-SQL-2nd-Beginners-Storytelling/dp/1718501064) by Anthony DeBarros

I'm currently working with another collegue to sharpen and practice our SQL skills.
Although I'm up-to-date on most of the basics and am usually pretty good at completing straight-forward queries, it was a good time to focus and become even more proficient with the language.
So, we picked up this book to learn more.

#### [R for Data Science (2e)](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund

Currently, I'm leading another [Data Science Learning Community](https://dslc.io/) bookclub meeting for this book.
I haven't read the second edition yet, so I'm excited to see and learn what's new.

#### [With the Old Breed: At Peleliu and Okinawa](https://www.amazon.com/Old-Breed-At-Peleliu-Okinawa/dp/0891419195) by E.B. Sledge

This is a personal read I pick up from time to time.
I finished watching the HBO miniseries Band of Brothers and The Pacific, which were based on first hand accounts in books like this.
With the Old Breed is a first-hand account of one serviceman's experience on the frontline during operations in the Pacific Theater, specifically in Peleliu and Okinawa, during World War II.
It's unfathomable to comprehend the experiences and hardships many endured.
Reading it has made me more deeply appreciate the sacrafices men and women of the armed services make for the United States of America.

### Professional development reads

#### [Machine Learning with R - Fourth Edition](https://www.amazon.com/Machine-Learning-cleansing-modeling-tidyverse/dp/1801071322/) by Brett Lantz 

#### [Practical Tableau](https://www.amazon.com/Practical-Tableau-Tutorials-Strategies-Master/dp/1491977310) by Ryan Sleeper

#### [HBR Guide to Making Every Meeting Matter](https://www.amazon.com/Guide-Making-Every-Meeting-Matter/dp/1633692175) from the Harvard Business Review

#### [The Checklist Manifesto: How to Get Things Right](https://www.amazon.com/Checklist-Manifesto-How-Things-Right/dp/0312430000) by Atul Gawande 

#### [Tidy Modeling with R](https://www.tmwr.org/) by Max Kuhn and Julia Silge

#### [Python for Data Analysis](https://wesmckinney.com/book/) by Wes McKinney

#### [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/) by Colin Fay, Sébastien Rochette, Vincent Guyader, and Cervan Girard

#### [Advanced R](https://adv-r.hadley.nz/) by Hadley Wickham. Check out past book club meeting recordings [here](https://www.youtube.com/playlist?list=PL3x6DOfs2NGi4I1DhjPufFNbqCry_xQLq).

#### [R Packages](https://r-pkgs.org/) by Hadley Wickham and Jenny Bryan. Check out past book club meeting recordings [here](https://www.youtube.com/watch?v=QOmdmGMxl_Q&list=PL3x6DOfs2NGi8NcKmNxw_Hk4-leUsivZv&index=1).

#### [Vim help files](https://vimhelp.org/) maintained by Carlo Teubner

#### [Mastering Ubuntu](https://www.amazon.com/Mastering-Ubuntu-Server-configuring-troubleshooting/dp/1800564643) by Jay LaCroix

#### [Google BigQuery: The Definitive Guide](https://www.amazon.com/Google-BigQuery-Definitive-Warehousing-Analytics/dp/1492044466/) by Valliappa Lakshmanan and Jordan Tigani

#### [Mastering Shiny](https://mastering-shiny.org/) by Hadley Wickham. Check out the past book club meeting recordings [here](https://www.youtube.com/watch?v=beOYuHG9Xng&list=PL3x6DOfs2NGjhwrYvdmrKRNcvXX7X6ldt).

#### [R for Data Science](https://r4ds.had.co.nz/) by Hadley Wickham and Garrett Grolemund. Check out the past book club meeting recordings [here](https://www.youtube.com/watch?v=_IQrDw3Fp4M&list=PL3x6DOfs2NGjtn1_4BSX99R5wrLjK7XvY).

#### [Docker Deep Dive](https://www.amazon.com/Docker-Deep-Dive-Nigel-Poulton-ebook/dp/B01LXWQUFF) by Nigel Poulton

### Personal reads

#### [The Currents of Space (Galactic Empire 2)](https://www.amazon.com/Currents-Space-Galactic-Empire-Book-ebook/dp/B08GK12F2P) by Issac Asimov

#### [The Stars, Like Dust (Galactic Empire 1)](https://www.amazon.com/The-Stars-Like-Dust/dp/B08CFSK8GG/) by Issac Asimov

#### [Robots and Empire (The Robot Series 4)](https://www.amazon.com/Robots-Empire-I-Asimov/dp/0008277796/) by Issac Asimov

#### [The Robots of Dawn (The Robot Series 3)](https://www.amazon.com/Robots-Dawn-Robot-Isaac-Asimov/dp/0553299492/) by Isaac Asimov 

#### [The Naked Sun (The Robot Series Book 2)](https://www.amazon.com/Naked-Sun-Robot-Book-ebook/dp/B004JHYRDQ/) by Isaac Asimov 

#### [The Caves of Steel (The Robot Series Book 1)](https://www.amazon.com/Caves-Steel-Daneel-Olivaw-Book/dp/0553293400) by Isaac Asimov 

#### [I, Robot](https://www.amazon.com/I-Robot-Book-1-ebook/dp/B000FC1PW0/) by Isaac Asimov

#### [Leviathan Falls (The Expanse book 9)](https://www.amazon.com/Leviathan-Falls-Expanse-Book-9/dp/B0971RBRV8) by James S.A. Corey

#### [Tiamat's Wrath (The Expanse book 8)](https://www.amazon.com/Tiamats-Wrath-Expanse-Book-8-ebook/dp/B07BVNVWL6) by James S.A. Corey

#### [Persepolis Rising (The Expanse book 7)](https://www.amazon.com/Persepolis-Rising-Expanse-James-Corey/dp/0316332852) by James S.A. Corey

#### [Babylon's Ashes (The Expanse book 6)](https://www.amazon.com/Babylons-Ashes-Expanse-James-Corey/dp/031633474X) by James S.A. Corey

#### [Nemesis Games (The Expanse book 5)](https://www.amazon.com/Nemesis-Games-Expanse-Book-5-ebook/dp/B00O7X626W/) by James S.A. Corey

#### [Cibola Burn (The Expanse book 4)](https://www.amazon.com/Cibola-Burn-Expanse-James-Corey/dp/0316334685) by James S.A. Corey

#### [Abaddon's Gate (The Expanse book 3)](https://www.amazon.com/Abaddons-Gate-Expanse-James-Corey/dp/0316129070) by James S.A. Corey

#### [Caliban's War (The Expanse book 2)](https://www.amazon.com/Calibans-War-Expanse-Book-2-ebook/dp/B005SCRR1A) by James S.A. Corey

#### [Leviathon Wakes (The Expanse book 1)](https://www.amazon.com/Leviathan-Wakes-Expanse-Book-1-ebook/dp/B0047Y171G) by James S.A. Corey

#### [The Galaxy, and the Ground Within: A Novel (Wayfarers 4)](https://www.amazon.com/Galaxy-Ground-Within-Novel-Wayfarers-ebook/dp/B088RDCLQ4) by Becky Chambers

#### [Record of a Spaceborn Few (Wayfarers 3)](https://www.amazon.com/Record-Spaceborn-Few-Wayfarers-Book-ebook/dp/B072BFJCB9/) by Becky Chambers

#### [A Closed and Common Orbit (Wayfarers 2)](https://www.amazon.com/dp/B01ARXVTFE/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1) by Becky Chambers

#### [The Long Way to a Small, Angry Planet (Wayfarers 1)](https://www.amazon.com/Long-Small-Angry-Planet-Wayfarers/dp/0062444131) by Becky Chambers

#### [Last of the Breed](https://www.amazon.com/Last-Breed-Novel-Louis-LAmour/dp/0553280422) by Louis L'Amour

#### [Project Hail Mary](https://www.amazon.com/Project-Hail-Mary-Andy-Weir-ebook/dp/B08FHBV4ZX/) by Andy Weir

#### [Firebreak](https://apps.npr.org/best-books/#year=2021&book=93) by Nicole Kornher-Stace

#### [Dune Messiah](https://www.amazon.com/gp/product/B0011UGNDG) by Frank Herbert

#### [Dune](https://www.amazon.com/gp/product/B00B7NPRY8) by Frank Herbert

#### [The Martian: A Novel](https://www.amazon.com/Martian-Novel-Andy-Weir-ebook/dp/B00EMXBDMA) by Andy Weir
