---
execute:
  eval: false
---

### Probability distributions

A probability distribution is another fundamental concept within probability.
Probability distributions are best represented in table form, where all the disjoint outcomes and their associated probabilities are listed.

To be considered a valid probability distribution, three criteria must be met.
These include:

1. The outcomes listed must be disjoint.
2. Each probability must be between 0 and 1.
3. The probabilities must total to 1.

The canonical and most accessible example of a probability distribution is the sum of rolling two dice.
Here is some R code to simulate this, while also providing a histogram of the probabilities for each outcome.

When it comes to rolling two dice, there are 11 possible outcomes: two die roll outcomes = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}.
Or, represented in R code, it would look something like this:

```{r}
#| label: sim-two-die
data_two_dice <- tibble(
  die1 = sample(1:6, 10000, replace = TRUE),
  die2 = sample(1:6, 10000, replace = TRUE)
) |>
  mutate(total = die1 + die2)

table(data_two_dice$total)
table(data_two_dice$total) / 10000
hist(data_two_dice$total, breaks = 1.5:12.5)
```

### Complement

The complement involves the outcomes not part of the original observed events.
Let's go back to our single, six-sided die example.
Say we have an event A, which is defined as the following A = {1, 3, 5}.
In other words, the dice's odd numbers on a single six-sided die.
The complement of A would be the even values.
That is A^c = {2, 4, 6}.
Just like any probability calculation, the probability of a complement can be calculated, and can be useful when working with a more complex problem.

### Independence

Independence of outcomes is also a key term for probability theory.
That is, independence means that knowing the outcome of one event provides no useful information about the outcome of the other.
For instance, let's say we roll a 20-sided die twice.
What we roll the first time gives us no useful information on what our second roll will be.
This is because a roll of 2 is independent of a roll of 1.

## Conditional probability

## Tree diagrams
