---
title: "The Hex Update: Issue 003"
draft: true
date: "2025-11-01"
author: "Collin K. Berke, Ph.D."
description: "A weekly collection of what I recently read and learned about the media industry"
toc: true
from: markdown+emoji
categories:
  - the hex update
  - media
---

# Let's catch up

Hi.
So, I haven't done much with [The Hex Update](https://www.collinberke.com/blog/posts/2024-07-10-hex-update-001/) in a while.
The first couple of issues were a bit of a false start.
I wasn't being realistic with what I could achieve with the time available.
Here we go again.

I'm attempting to pick The Hex Update back up, with a focus toward simplification and being easy to manage.
As such, I'll be making a few changes.
I'm now aiming for a weekly issue, but limiting each post to three sections: Let's catch up; Three things from this week; and Just for fun.

The sections are as follows:

* Let's catch up: a space to discuss what's on my mind regarding media, entertainment, or other industry news.
* Three things from this week: links to articles, blogs, etc. I bumped into this week, each with a brief summary.
* Just for fun: one thing I found this week that I thought was fun. It may be media related or not. It's more of a place to end the week on a high note, maybe even a laugh.

I'm also intending for the article summaries to be shorter.
The goal is paragraph length.
This will be a challenge for me.
My writing can be a bit verbose at times.

With a renewed vision, let's highlight what I found interesting this week.

# Three things from this week

[Article: YouTube Just Ate TV. It's Only Getting Started from The Hollywood Reporter](https://www.hollywoodreporter.com/business/digital/youtube-impact-tv-sports-late-night-comedy-shows-1236400353/)

Here's an article focused on the rapid growth of YouTube, no longer just a place of user-generated content, but a dominant force in media.
The platform aims to expand its footprint by capturing the *other* hours people are spend watching their TVs.
Indeed, if you read [YouTube's big bets](https://blog.youtube/inside-youtube/our-big-bets-for-2025/), you'll be confronted with the fact that YouTube viewing on TVs has surpassed YouTube viewing on mobile devices, a fact, [Neal Mohan](https://www.linkedin.com/in/neal-mohan/), YouTube's CEO is leaning into.
In addition, it's staggering that YouTube claims 1 billion podcast users monthly.
There's some further discussion about how various media formats (e.g., cooking, children's content, and late night) are now finding success and moving toward a YouTube first strategy--though the platform is still challenged by scripted content.
However, there are some examples of creators trying to grow this space.
The article then wraps up with a conversation about content production, the economics of content creation, and the role creators and larger production studios play.

[Podcast: Why GM will give you Gemini, but not Carplay from Decoder with Nilay Patel](https://www.youtube.com/watch?v=GIr_oscnob4)

Here's a conversation between [Nilay Patel](https://www.theverge.com/authors/nilay-patel) and [General Motors](https://www.gm.com/) CEO [Mary Barra](https://www.linkedin.com/in/mary-barra/) and Chief Product Officer [Sterling Anderson](https://www.linkedin.com/in/sterlinganderson/).
The conversation centered around electric vehicles, current market dynamics, product development, and various GM product offerings.
Relevant to media was the integration of AI into new GM models and the step back from offering [Apple's Carplay](https://www.apple.com/ios/carplay/) within GM models.
Here are some points in the conversation I found worth review:

* The rollout of [Gemini AI](https://gemini.google.com/) into 2026 GM models and the step back from smart phone projection apps like Apple Car Play [(37M03S)](https://youtu.be/GIr_oscnob4?si=7XmmWQt6rzhnZ08e&t=2223)
* An interesting point for why users want access to the large library of apps provided with phone projection [(41M41S)](https://youtu.be/GIr_oscnob4?si=q7jfEGP2TE4RbxPG&t=2501)
* Natural language and LLM interfaces brought to the car and customized experiences to the user [(46M58S)](https://youtu.be/GIr_oscnob4?si=e6u02S_fyE5fLn6R&t=2818)

[]()

# Just for fun

If you found this content useful, please share.
If you find these topics interesting and want to discuss further, let's connect:

* BlueSky: [@collinberke.bsky.social](https://bsky.app/profile/collinberke.bsky.social)
* LinkedIn: [collinberke](https://www.linkedin.com/in/collinberke/)
* GitHub: [@collinberke](https://github.com/collinberke)
* [Say Hi!](https://www.collinberke.com/say-hi)
